# Generated by Django 2.2.2 on 2019-06-06 07:20

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.TextField()),
                ('oldPrice', models.PositiveIntegerField()),
                ('newPrice', models.PositiveIntegerField()),
                ('saleType', models.CharField(max_length=25)),
                ('quantity', models.PositiveIntegerField()),
                ('slug', models.SlugField()),
            ],
        ),
    ]
