//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace FurnitureDataAccess
{
    using System;
    using System.Collections.Generic;
    
    public partial class Furniture
    {
        public int id { get; set; }
        public string namefurniture { get; set; }
        public string descriptionfurniture { get; set; }
        public string typefurniture { get; set; }
        public Nullable<double> price { get; set; }
        public string seller { get; set; }
        public Nullable<int> nrofproducts { get; set; }
    }
}
